### ISSUE TITLE
Error in console: unable to preventDefault inside passive event listener invocation

### ISSUE THREAD

**Issue by sunnysette** [zzarcon/default-passive-events#2]
Yo bro, i've implemented your script on my WordPress site and i'm getting this error in console:

![image](https://cloud.githubusercontent.com/assets/24605932/21261018/419884c6-c389-11e6-85f1-33cb1cbd9a43.png)

Can you help me debug it?

**Comment by zzarcon** [comment]
Hi @sunnysette, that's probably happening because you are trying to call `preventDefault` into a passive event listener, which it's not allowed to do that. 

Removing the call to `preventDefault` should do the trick

**Comment by sunnysette** [comment]
Thank you mate.

I wasn't calling nothing, it was a script in the theme i use.
I've remove that script, is working well again. Thank Again.

**Comment by zzarcon** [comment]
You welcome, thanks for using the lib!
