### ISSUE TITLE
The routine doesn't work for YouTube videos embedded in iFrames

### ISSUE THREAD

**Issue by tmb-github** [zzarcon/default-passive-events#22]
The code doesn't work for YouTube videos embedded in an iFrame, like this:

`<iframe width="420" height="315" src="https://www.youtube.com/embed/DJYpXxWqvmo" allowfullscreen></iframe>`

This one iframe generates four instances of this console error:

> [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

Can this please be fixed? Many thanks!

**Comment by FRSgit** [comment]
Unfortunately that's not up to this project - using **iframe** succesfully **prevents** access of third-party code to the current iframe's document context, so we cannot override addEventListener method there as we're doing now.

If you want to encourage youtube to use passive events please star an issue I've created on google's issue tracker [here](https://issuetracker.google.com/u/0/issues/72450169) and hope they'll start using passive events ASAP.

**Comment by FRSgit** [comment]
I'm adding 'wontfix' label but not closing the issue - it will be closed only when youtube does their part.

**Comment by FRSgit** [comment]
@tmb-github lately chrome changed it's behaviour about showing errors for passive events, so can you please recheck if your problem still exists?

**Comment by FRSgit** [comment]
I guess it's about silencing, because reporting this case as an error is just wrong. If you let me I would like to ask you to check it again when 73 hits stable, because I don't have any test case for that.

So, I'll just ping you here at some point of March, okay?

**Comment by FRSgit** [comment]
For a moment now chrome stable is at version 73, @tmb-github can you please check if our problem is fixed already?

**Comment by tmb-github** [comment]
@FRSgit It is not. It has disappeared in Chrome Canary 75, however, but there's now a NEW error that appears 7 times: 
   cast_sender.js:39 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at $$jscomp$inherits$$ (cast_sender.js:39)
    at cast_sender.js:357
    at cast_sender.js:1693

**Comment by FRSgit** [comment]
Hm, that's weird. But I understand that previous error has disappeared?

`cast_sender.js` is not connected with our code at all - it has something with google cast plugin, but hard to tell. Maybe it will be fixed until 75 hit stable.
