### ISSUE TITLE
Doesn't work, even the example page

### ISSUE THREAD

**Issue by Bus42** [zzarcon/default-passive-events#26]
![screenshot 18](https://user-images.githubusercontent.com/20022081/49493209-6740be80-f818-11e8-8d93-e2fca1471ce9.png)

I was curious when it didn't work in my app. Not sure if it matters, but I installed *default-passive-events* via NPM. I'm building a React application in Windows 10 using Chrome Version 70.0.3538.110 (Official Build) (64-bit). Maybe it's because it's React, but that's why I wanted to try your package, anyway I went to your example and ran an audit and either you're not using it on your own example or it just doesn't work. Thought I'd share with you.

**Comment by FRSgit** [comment]
Just confirmed - library is working under Win 10 Chrome 70.0.3538.110 (see screenshot below).
Is it possible that you're using any of Chrome's extenstions/plugins that break our functonality?

![image](https://user-images.githubusercontent.com/10456649/49509878-ea006280-f886-11e8-96cd-6a6116f3f395.png)

**Comment by Bus42** [comment]
Hmm... I'll try another browser and let you know how it goes. Hopefully I
can find out why and let you know.

**Comment by FRSgit** [comment]
Do you have any news on that? Maybe there is some possibility to reproduce bug case?

**Comment by FRSgit** [comment]
Because of inactivity I'm closing this issue as invalid, if it's reproducible somehow, please submit new issue with reproduce steps
