### ISSUE TITLE
Cursor event not work while jquery is appending new content.

### ISSUE THREAD

**Issue by BoumBam** [zzarcon/default-passive-events#28]
I started using that plugin recently and it's a powerful plugin.

But after the ajax request and when new content is adding to a page cursor event not work during the appending of new content, only the scroll event works not the other events.
All my page is blocked(for some seconds) until the appending process finish.

How could i do to make cursor event working while the jquery is appending new content ?

Thanks.

**Comment by FRSgit** [comment]
Hi @BoumBam,

Thanks for warm words, it's great that out library has a use in your case!

Can you maybe provide us any reproduce scenario (can be on codepen/stackblitz online environment)?

**Comment by FRSgit** [comment]
Sorry to say, but due to no response I need to close this issue. Feel free to respond if you still want to elaborate on this problem!
