### ISSUE TITLE
this is not an issue as it seems

### ISSUE THREAD

**Issue by Venom7719** [zzarcon/default-passive-events#30]
If you have time
please share how to add this setup on a wordpress site if possible
thanks in advance

**Comment by FRSgit** [comment]
Hey,
Unfortunately I'm not a wordpress expect, but after quick googling I found out this:
https://www.ostraining.com/blog/wordpress/custom-js/

You could follow this tutorial and via the plugin pointed out there add custom script file, here is the link to the `default-passive-events` hosted on UNPKG CDN:
https://unpkg.com/default-passive-events@1.0.10/dist/index.js

Hope this helps!

**Comment by FRSgit** [comment]
Hey, have it helped you? Please give a sign! 📡 
I'm closing this issue, feel free to reopen if needed
