### ISSUE TITLE
Question: where should I place the script to get the best result

### ISSUE THREAD

**Issue by lenamtl** [zzarcon/default-passive-events#33]
Hi,

I'm having issue when using your plugin with Select2.

I'm using jQuery and several plugins so what will be the best position for default-passive-events file?
Prior any JS script first item
After JQuery
The last item

Thanks

**Comment by FRSgit** [comment]
Well, for the best performance you should add the script before any other javascript. But you need to remember to check if all of your plugins pair well with the `default-passive-events` - some of them might not (as you specified in your issue about `Select2` plugin).
Of course, the most "non-breaking way" of importing `default-passive-events` library would be if you run it after all other javascript - but then then would be no gain from using this library. The main benefit here is to use passive event listeners whenever possible. After all listeners get added, our library won't do anything.

The issue with `Select2` is handled in separated ticket and this question is answered. I will close this one then, cheers!
