### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by pragya-techahead** [zzarcon/default-passive-events#5]
When I used this repository, after clicking on any <a> link</a> on the site. I got this error

**Comment by zzarcon** [comment]
Thats because is setting ```{passive: true}``` to all events on the page. In order to **preventDefault** in a specific event, you will need to add ```{passive: false}```:

```javascript
const onClick = e => e.preventDefault();

document.addEventListener('click', onClick, {passive: false});
```
