### ISSUE TITLE
Unable to preventDefault inside passive event listener

### ISSUE THREAD

**Issue by lizhuoyun-kiki** [zzarcon/default-passive-events#52]
i use default-passive-events,control will say "Unable to preventDefault inside passive event listener"
when i uninstall this,it will warn "Added non-passive event listener to a scroll-blocking 'mousewheel' eve"

how can i solve this problem

**Comment by FRSgit** [comment]
Hey @lizhuoyun-kiki, what part of the code is the warning originating from?
It's very probable that some of the libraries you're using (or your own code) does indeed use `e.preventDefault()` within a passive listener.

But don't worry - the "error" you're seeing is not an actual thrown Error. It is just a `console.error` message - so something that just looks like an error in the console, nothing more. You don't need to be worrying about it at all :)
