### ISSUE TITLE
Can this package prevent warnings in combination with other frameworks?

### ISSUE THREAD

**Issue by fergardi** [zzarcon/default-passive-events#7]
Hello!

I'm facing this issue in my current development: https://github.com/museui/muse-ui/issues/761

Can this package be used to prevent another framework from generating non passive event listeners? I've installed it but it gives me the same output:

![image](https://user-images.githubusercontent.com/3602272/31582785-3a3c7d66-b18d-11e7-9fda-5e2081cae467.png)

I've debugged the extension and it always passes false to the event listener creation.

![image](https://user-images.githubusercontent.com/3602272/31582799-91858428-b18d-11e7-8b88-b674f10e7759.png)

What is happening here?

Thanks.

**Comment by fergardi** [comment]
I refactored the plugin to add it manually:

> options.passive = true // options.passive !== undefined ? options.passive : defaultOptions.passive;

And now it correctly sets the event listener to a passive one. But why it does not work directly like that?

**Comment by zzarcon** [comment]
Hi @fergardi thanks for reporting this. I believe we currently do:

```javascript
options.passive = options.passive !== undefined ? options.passive : defaultOptions.passive
```

Because we still want people to be able to declare **non passive** listeners, like:

```
require('default-passive-events');

document.addEventListener('click', onClick); // This will be passive by default

document.addEventListener('click', onClick, {passive: false}); // This will override the default "passive: true" 
```

Have a look into https://github.com/zzarcon/default-passive-events#usage.

Does this makes sense to you? Please, feel free to open PR or point if Im missing something!

**Comment by fergardi** [comment]
Hello, thank for your response.

![image](https://user-images.githubusercontent.com/3602272/31682368-280fdd92-b37a-11e7-8380-a293c02bd3a3.png)

I was trying to get rid of the verbose warnings Chrome added about non-passive event listeners, and thought that using your plugin before adding the UI framework I am using would work. And works indeed, but at the cost of disabling all event handlers the framework is using, becoming useless in the process. It seems it is the framework developer who needs to implement this plugin or, at least, change all the declarations of his event listeners passive by default.

This only delays my app in development mode, and only if I've checked the "verbose" filter in Chrome Dev Tools, but usually I want as little warnings as possible, so I did a little research and found your plugin in the meantime.

Or maybe I don't even know how to use it properly in combination with other libraries using eventListeners.

Thank you anyway!

**Comment by zzarcon** [comment]
That is interesting. I believe the approach you followed was the right one:

1- Add **default-passive-events**
2- Load the UI framework
3- All the events declared by the framework should contain **{default: true}**

I'd like to know why the framework events gets **disabled**. If you want to do a further investigation I will be more than happy to merge a PR fixing this issue (in the case that is a problem with the library).
